"""Prose conclusion report (PDF).

`out/run-*.json` and `out/proof-*.json` are machine artifacts: correct, complete
and unreadable. This module turns the same run dict into a short A4 document a
non-technical reader can sit down with - a verdict, three to five paragraphs of
actual English explaining what happened and whether it holds up, the key figures
in a table, the two faces side by side, and an honest note on the limits.

    from facechain.report_pdf import build_conclusion, conclusion_text

    build_conclusion(run, Path("out/conclusion-abc123.pdf"))
    for para in conclusion_text(run):
        print(para)

Nothing here invents a number. Every figure is read out of `run` with .get()
chains, and a field that is missing is described as missing rather than guessed.
"""

from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional, Sequence

from reportlab.lib import colors
from reportlab.lib.enums import TA_JUSTIFY, TA_LEFT
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.units import mm
from reportlab.lib.utils import ImageReader
from reportlab.pdfbase import pdfmetrics
from reportlab.platypus import (BaseDocTemplate, Flowable, Frame, KeepTogether,
                                PageTemplate, Paragraph, Spacer, Table,
                                TableStyle)

# --- Palette -------------------------------------------------------------
# Screen cyan (#00e5ff) is unreadable on white paper; #00B8CC is the print form.
INK = colors.HexColor("#0d0d0d")
STEEL = colors.HexColor("#6b7178")
CYAN = colors.HexColor("#00B8CC")
RED = colors.HexColor("#C0392B")
HAIRLINE = colors.HexColor("#d7dade")
WASH = colors.HexColor("#f5f6f7")

PAGE_W, PAGE_H = A4
MARGIN = 20 * mm
HEADER_H = 26 * mm
FOOTER_H = 16 * mm

FOOTER_NOTE = ("Generated by the FaceChain pipeline itself. Every figure in this "
               "report is read from the run record; none was typed in by hand.")


# --- Small formatting helpers -------------------------------------------

_WORDS = ["no", "one", "two", "three", "four", "five", "six", "seven", "eight",
          "nine", "ten", "eleven", "twelve", "thirteen", "fourteen", "fifteen",
          "sixteen", "seventeen", "eighteen", "nineteen", "twenty"]


def _num(n: Any, cap: bool = False) -> str:
    """Small integers read better as words in prose; large ones as digits."""
    try:
        i = int(n)
    except (TypeError, ValueError):
        return "An unrecorded number" if cap else "an unrecorded number"
    word = _WORDS[i] if 0 <= i < len(_WORDS) else "{:,}".format(i)
    return word[:1].upper() + word[1:] if cap else word


def _plural(n: Any, one: str, many: str) -> str:
    try:
        return one if int(n) == 1 else many
    except (TypeError, ValueError):
        return many


def _short(value: Any, head: int = 12, tail: int = 4) -> str:
    """Abbreviate a hash for prose while keeping both ends checkable."""
    s = str(value or "")
    if not s:
        return "(not recorded)"
    if len(s) <= head + tail + 1:
        return s
    return s[:head] + "…" + s[-tail:]


def _join(items: Sequence[str], conj: str = "and") -> str:
    vals = [str(i) for i in items if str(i or "").strip()]
    if not vals:
        return ""
    if len(vals) == 1:
        return vals[0]
    if len(vals) == 2:
        return vals[0] + " " + conj + " " + vals[1]
    return ", ".join(vals[:-1]) + " " + conj + " " + vals[-1]


def _pretty_date(iso: Any) -> Optional[str]:
    """'2026-09-07T14:02:00.000Z' -> '7 September 2026 at 14:02 UTC'."""
    s = str(iso or "").strip()
    if not s:
        return None
    txt = s.replace("Z", "+00:00")
    for cut in (txt, txt.split(".")[0] + ("+00:00" if "+" in txt or "Z" in s else "")):
        try:
            dt = datetime.fromisoformat(cut)
        except (ValueError, TypeError):
            continue
        if dt.tzinfo is not None:
            dt = dt.astimezone(timezone.utc)
        return "%d %s %d at %02d:%02d UTC" % (dt.day, dt.strftime("%B"), dt.year,
                                              dt.hour, dt.minute)
    return None


def _ratio_phrase(sim: float, thr: float) -> str:
    """Say what the margin means without arithmetic on the reader's part."""
    if not thr:
        return "a margin that cannot be expressed as a ratio because the threshold is zero"
    r = sim / thr
    if r < 1.0:
        return "below the line rather than above it, at %.2f times the threshold" % r
    if r < 1.15:
        return "only just over the line, at %.2f times the threshold" % r
    if r < 1.6:
        return "comfortably clear of it, at %.2f times the threshold" % r
    if r < 1.9:
        return "well clear of it, at %.2f times the threshold" % r
    if r < 2.15:
        return "a little over twice the score required"
    if r < 2.6:
        return "more than twice the score required (%.2f times)" % r
    return "%.1f times the score required" % r


def _gas(value: Any) -> Optional[str]:
    try:
        g = int(value)
    except (TypeError, ValueError):
        return None
    return "{:,}".format(g) if g > 0 else None


def _esc(text: Any) -> str:
    s = str(text if text is not None else "")
    return s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")


class _Mono:
    """Wraps hashes/URLs in Courier for the PDF, leaves them bare for console."""

    def __init__(self, markup: bool) -> None:
        self.markup = markup

    def __call__(self, value: Any) -> str:
        if not self.markup:
            return str(value if value is not None else "")
        return '<font face="Courier">' + _esc(value) + "</font>"

    def text(self, value: Any) -> str:
        return _esc(value) if self.markup else str(value if value is not None else "")


# --- Verdict -------------------------------------------------------------

def verdict_of(run: Dict[str, Any]) -> Dict[str, Any]:
    """Reduce the whole run to one unambiguous line plus a one-sentence gloss."""
    run = run or {}
    search = run.get("search") or {}
    best = search.get("best_match") or {}
    chain = run.get("chain") or {}
    ver = chain.get("verification") or {}
    receipt = chain.get("receipt") or {}
    status = str(run.get("status") or ("ok" if best else "no-match"))

    if not best or status == "no-match":
        return {
            "headline": "NO MATCH FOUND",
            "gloss": ("The search ran to completion but no image it examined was "
                      "the same person as the one submitted, so nothing was "
                      "written to the chain."),
            "passed": False,
            "neutral": True,
        }

    verified = bool(ver.get("verified"))
    tamper_ok = bool(chain.get("tamper_detected", True))
    if not receipt:
        return {
            "headline": "MATCHED - NOT ANCHORED",
            "gloss": ("The face was identified in a live post, but no blockchain "
                      "receipt was recorded for this run, so the finding is not "
                      "yet independently checkable."),
            "passed": False,
            "neutral": False,
        }
    if verified and tamper_ok:
        return {
            "headline": "IDENTITY MATCHED AND ANCHORED",
            "gloss": ("The submitted face was matched to a real, live post, the "
                      "evidence was committed to a blockchain, and re-reading the "
                      "chain reproduced exactly the same digest."),
            "passed": True,
            "neutral": False,
        }
    if verified and not tamper_ok:
        return {
            "headline": "MATCHED - TAMPER CHECK INCONCLUSIVE",
            "gloss": ("The evidence verifies against the chain, but the deliberate "
                      "tamper test was not rejected as it should have been; treat "
                      "the anchor with caution."),
            "passed": False,
            "neutral": False,
        }
    return {
        "headline": "MATCHED - VERIFICATION FAILED",
        "gloss": ("A face match was found, but the digest recomputed from the "
                  "evidence does not agree with the value held on the chain."),
        "passed": False,
        "neutral": False,
    }


# --- The prose -----------------------------------------------------------

def _para_submission(run: Dict[str, Any], m: _Mono) -> str:
    face = (run.get("face") or {})
    src = face.get("source_path")
    sha = face.get("image_sha256")
    found = face.get("faces_found")
    conf = face.get("detection_confidence")
    det = face.get("detector")
    enc = face.get("encoder")
    dim = face.get("embedding_dim")
    fp = face.get("embedding_sha256")
    bbox = face.get("bbox") or []

    opening = "A single photograph was submitted to the pipeline"
    opening += (", %s" % m(src)) if src else ", though the run record does not name the file"
    if sha:
        opening += ", whose bytes hash to sha256 %s" % m(_short(sha, 16, 6))
    s = [opening + "."]

    detect = ("The %s detector" % m(det)) if det else "The detector, which the record does not name,"
    if isinstance(found, int):
        detect += " found %s %s in it" % (_num(found), _plural(found, "face", "faces"))
    else:
        detect += " found a face in it"
    if isinstance(conf, (int, float)):
        detect += ", at a detection confidence of %.2f" % conf
    if len(bbox) == 4:
        detect += ", and cropped it at pixel box %s" % m(
            "[%s]" % ", ".join(str(int(b)) for b in bbox))
    s.append(detect + ".")

    encode = "That crop was handed to the %s encoder" % m(enc) if enc else \
        "That crop was handed to the face encoder"
    encode += (", which reduced it to %s numeric vector"
               % ("a %d-dimensional, unit-length" % dim
                  if isinstance(dim, int) else "a unit-length"))
    encode += (" - the fingerprint every later comparison in this run is made "
               "against, and the only form of the face the pipeline actually "
               "compares.")
    s.append(encode)
    if fp:
        s.append("That vector itself hashes to %s, which lets the same face be "
                 "cited in this report without reproducing the biometric data "
                 "behind it." % m(_short(fp, 16, 6)))
    return " ".join(s)


def _para_search(run: Dict[str, Any], m: _Mono) -> str:
    search = run.get("search") or {}
    providers = [p for p in (search.get("providers") or []) if p]
    queries = [q for q in (search.get("queries") or []) if q]
    seen = search.get("candidates_seen")
    got = search.get("candidates_downloaded")
    faces = search.get("candidates_with_faces")
    secs = search.get("elapsed_seconds")

    s = ["The search that followed was live: the pipeline queried public "
         "providers over the network rather than looking the face up in a "
         "prepared index."]
    if providers:
        s.append("%s %s responded - %s - and between them returned %s" % (
            _num(len(providers), cap=True),
            _plural(len(providers), "provider", "providers"),
            _join([m(p) for p in providers]),
            "{:,} candidate {}".format(seen, _plural(seen, "result", "results"))
            if isinstance(seen, int) else "an unrecorded number of candidate results"))
        if queries:
            shown = queries[:3]
            s[-1] += " for %s such as %s" % (
                _plural(len(queries), "the query", "queries"),
                _join(['“%s”' % m.text(q) for q in shown], "and"))
        s[-1] += "."
    else:
        s.append("No provider names were recorded for this run, which is itself "
                 "worth noting.")

    downloaded = ("%s %s" % (_num(got), _plural(got, "image was", "images were"))
                  if isinstance(got, int) else "an unrecorded number of images were")
    pipeline = ("Of those, %s actually downloaded and re-encoded, and %s of them "
                "contained a face the detector could locate"
                % (downloaded, _num(faces)))
    if isinstance(secs, (int, float)) and secs:
        pipeline += "; the whole sweep took %.1f seconds" % secs
    s.append(pipeline + ".")
    s.append("Each of those faces was then compared to the submitted embedding "
             "directly. No result was accepted because its caption, filename, "
             "page title or surrounding text mentioned the name being searched "
             "for - the words were used only to find pictures, and were ignored "
             "the moment a picture had been fetched.")
    return " ".join(s)


def _para_finding(run: Dict[str, Any], m: _Mono) -> str:
    search = run.get("search") or {}
    best = search.get("best_match") or {}
    thr = search.get("threshold")
    sim = best.get("similarity")
    matches = search.get("matches") or []
    notes = [str(n) for n in (search.get("notes") or [])]

    platform = best.get("platform") or "an unnamed platform"
    url = best.get("post_url") or ""
    when = _pretty_date(best.get("posted_at"))
    author = best.get("author") or ""
    title = (best.get("title") or "").strip()

    lead = "The strongest result was a post on %s" % m(platform)
    if when:
        lead += " published on %s" % when
    else:
        lead += ", carrying no publication timestamp the provider would disclose"
    if author:
        lead += ", by %s" % m(author)
    if url:
        lead += ", at %s" % m(url)
    s = [lead + "."]
    if title:
        clipped = title if len(title) <= 150 else title[:147] + "…"
        s.append("It is captioned “%s”, though that text played no part in "
                 "the decision." % m.text(clipped))

    if isinstance(sim, (int, float)) and isinstance(thr, (int, float)):
        s.append("The face in its image scored a cosine similarity of %.4f against "
                 "the submitted face, where %.3f is the SFace reference value at "
                 "which two images are called the same identity - %s." % (
                     sim, thr, _ratio_phrase(float(sim), float(thr))))
    elif isinstance(sim, (int, float)):
        s.append("The face in its image scored a cosine similarity of %.4f, but no "
                 "threshold was recorded for this run." % sim)
    else:
        s.append("No similarity score was recorded for the best match, which "
                 "should not happen and is reported here rather than filled in.")

    n_above = len(matches)
    if n_above > 1:
        s.append("In all, %s %s cleared that threshold, which is what one expects "
                 "when the subject appears in public photography often; the rest "
                 "of the field fell away below it." % (
                     _num(n_above), _plural(n_above, "candidate", "candidates")))
    elif n_above == 1:
        s.append("It was the only candidate in the whole sweep to clear that "
                 "threshold.")

    passed_over = next((n for n in notes if "higher-scoring" in n), "")
    if passed_over:
        alt_sim = None
        alt_where = ""
        try:
            frag = passed_over.split("higher-scoring", 1)[1]
            for token in frag.replace("(", " ").replace(")", " ").split():
                cand = token.strip(",;")
                if cand.replace(".", "", 1).isdigit() and "." in cand:
                    alt_sim = float(cand)
                    break
            if "(" in passed_over:
                alt_where = passed_over.rsplit("(", 1)[1].rstrip(").")
        except (IndexError, ValueError):
            pass
        line = ("One candidate scored higher still and was passed over "
                "deliberately: the brief is to surface a social-media post, and a "
                "news or article page is not one")
        if alt_sim is not None:
            line += (", so the %.4f scored by %s was set aside in favour of the "
                     "social result named above" % (alt_sim,
                                                    m(alt_where or "a non-social page")))
        s.append(line + ".")
    return " ".join(s)


def _para_no_match(run: Dict[str, Any], m: _Mono) -> str:
    search = run.get("search") or {}
    thr = search.get("threshold")
    near = search.get("near_misses") or []
    faces = search.get("candidates_with_faces")
    seen = search.get("candidates_seen")

    s = ["Nothing cleared the bar."]
    if isinstance(thr, (int, float)):
        s.append("Every face the pipeline was able to extract scored below the "
                 "%.3f cosine similarity at which two images would be called the "
                 "same person, so no post was accepted as a match." % thr)
    else:
        s.append("No candidate scored high enough to be accepted as the same "
                 "person, and no threshold value was recorded for this run.")
    if near:
        top = near[0] or {}
        sim = top.get("similarity")
        url = top.get("post_url") or ""
        line = "The closest anything came was"
        line += (" %.4f" % sim) if isinstance(sim, (int, float)) else " an unrecorded score"
        if url:
            line += ", at %s" % m(url)
        s.append(line + ", which is nearer to the score two strangers produce "
                          "than to a genuine identity match.")
    s.append("This is a negative result, not a failure of the run: %s were "
             "harvested and %s of them yielded a face that was measured, so the "
             "counters in the table below show the search genuinely looked before "
             "it came back empty." % (
                 "{:,} {}".format(seen, _plural(seen, "candidate", "candidates"))
                 if isinstance(seen, int) else "an unrecorded number of candidates",
                 _num(faces)))
    s.append("Because there was no verified match, there was nothing worth "
             "committing to a blockchain, and the pipeline stopped rather than "
             "anchoring a guess.")
    return " ".join(s)


def _para_chain(run: Dict[str, Any], m: _Mono) -> str:
    chain = run.get("chain") or {}
    receipt = chain.get("receipt") or {}
    if not receipt:
        return ("No blockchain receipt was recorded for this run, so the finding "
                "above stands on the evidence files alone and cannot yet be "
                "checked against an independent, append-only record.")

    backend = receipt.get("backend") or "an unnamed backend"
    chain_id = receipt.get("chain_id")
    contract = receipt.get("contract_address")
    tx = receipt.get("tx_hash")
    block = receipt.get("block_number")
    rhash = receipt.get("record_hash")
    rid = receipt.get("record_id")
    gas = _gas(receipt.get("gas_used"))
    submitter = receipt.get("submitter")

    s = ["The findings were then reduced to a small canonical record - the hash "
         "of the submitted image, the fingerprint of its embedding, the detector "
         "and encoder that produced it, the matched post's platform, URL, author "
         "and timestamp, the hash of the matched image, and the similarity and "
         "threshold that decided the verdict - and that record was serialised in "
         "one fixed byte-for-byte form and hashed."]
    if rhash:
        s.append("The digest is %s." % m(_short(rhash, 18, 6)))
    anchor = "That digest, and not the record itself, was written to a registry contract"
    if contract:
        anchor += " at %s" % m(contract)
    anchor += " on %s" % m(backend)
    if isinstance(chain_id, int):
        anchor += " (chain id %d)" % chain_id
    if tx:
        anchor += ", in transaction %s" % m(_short(tx, 14, 6))
    if block is not None:
        anchor += ", mined into block %s" % m(str(block))
    if gas:
        anchor += " for %s gas" % gas
    if submitter:
        anchor += ", submitted by %s" % m(_short(submitter, 10, 4))
    s.append(anchor + ".")
    if rid:
        s.append("The record is addressed on chain by the id %s." % m(_short(rid, 18, 6)))
    s.append("What the chain now holds is a commitment, not a copy: no face, no "
             "image and no personal data was published by that transaction, only "
             "a fixed-length hash that any holder of the same evidence can "
             "recompute and that no one can recompute without it.")
    return " ".join(s)


def _para_verification(run: Dict[str, Any], m: _Mono) -> str:
    chain = run.get("chain") or {}
    ver = chain.get("verification") or {}
    tam = chain.get("tamper_check") or {}
    if not ver:
        return ("No re-verification step was recorded for this run, so the anchor "
                "above has not been read back and confirmed within this report.")

    computed = ver.get("computed_hash")
    onchain = ver.get("onchain_hash")
    block = ver.get("block_number")
    verified = bool(ver.get("verified"))
    exists = ver.get("exists_onchain")

    if verified:
        s = ["The proof was then tested rather than asserted."]
        line = ("The digest was recomputed from the evidence in hand and compared "
                "against the value read back out of the contract, and the two "
                "agreed")
        if computed:
            line += ": %s on both sides" % m(_short(computed, 18, 6))
        if block is not None:
            line += ", in block %s" % m(str(block))
        s.append(line + ".")
    else:
        s = ["The re-verification did not pass, and that is the finding."]
        s.append("The digest recomputed from the evidence, %s, does not match the "
                 "%s held on chain%s, so the evidence in hand is not the evidence "
                 "that was anchored." % (
                     m(_short(computed, 18, 6)), m(_short(onchain, 18, 6)),
                     "" if exists else " (and no record was found at that id)"))

    if tam:
        t_computed = tam.get("computed_hash")
        t_onchain = tam.get("onchain_hash")
        rejected = not bool(tam.get("verified"))
        line = ("To show the check has teeth, one field of the record was then "
                "altered - a single query string appended to the matched post's "
                "URL, changing nothing else")
        if t_computed and t_onchain:
            line += (" - and the digest recomputed as %s against the anchored "
                     "%s" % (m(_short(t_computed, 18, 6)), m(_short(t_onchain, 18, 6))))
        s.append(line + ".")
        if rejected:
            s.append("The chain rejected it. One character of difference in one "
                     "URL is enough to break the proof, which is exactly the "
                     "property an anchor is there to provide, and it is why the "
                     "match above can be trusted as the one that was recorded "
                     "and not a later edit of it.")
        else:
            s.append("The altered record was nevertheless accepted, which should "
                     "not be possible and means the tamper-evidence of this run "
                     "cannot be relied on.")
    return " ".join(s)


def _paragraphs(run: Dict[str, Any], markup: bool) -> List[str]:
    run = run or {}
    m = _Mono(markup)
    search = run.get("search") or {}
    has_match = bool(search.get("best_match")) and str(run.get("status") or "ok") != "no-match"

    paras = [_para_submission(run, m), _para_search(run, m)]
    if has_match:
        paras.append(_para_finding(run, m))
        paras.append(_para_chain(run, m))
        paras.append(_para_verification(run, m))
    else:
        paras.append(_para_no_match(run, m))
    return paras


def conclusion_text(run: Dict[str, Any]) -> List[str]:
    """The written conclusion as plain paragraphs, for console or web reuse."""
    return _paragraphs(run, markup=False)


# --- Evidence table ------------------------------------------------------

def evidence_rows(run: Dict[str, Any]) -> List[List[str]]:
    run = run or {}
    face = run.get("face") or {}
    search = run.get("search") or {}
    best = search.get("best_match") or {}
    chain = run.get("chain") or {}
    receipt = chain.get("receipt") or {}

    def fmt(v: Any, spec: Optional[str] = None, dash: str = "not recorded") -> str:
        if v is None or v == "" or v == []:
            return dash
        if spec and isinstance(v, (int, float)):
            return spec % v
        return str(v)

    rows: List[List[str]] = [
        ["input image", fmt(face.get("source_path"))],
        ["input sha256", fmt(face.get("image_sha256"))],
        ["face fingerprint", fmt(face.get("embedding_sha256"))],
        ["detector / encoder", "%s / %s" % (fmt(face.get("detector"), dash="?"),
                                            fmt(face.get("encoder"), dash="?"))],
        ["embedding", fmt(face.get("embedding_dim"), "%d-d L2-normalised")],
        ["identity threshold", fmt(search.get("threshold"), "cosine >= %.3f")],
    ]
    if best:
        rows += [
            ["best match platform", fmt(best.get("platform"))],
            ["best match url", fmt(best.get("post_url"))],
            ["best match posted", fmt(best.get("posted_at"), dash="no timestamp given")],
            ["similarity", fmt(best.get("similarity"), "%.4f")],
            ["matched image sha256", fmt(best.get("image_sha256"))],
        ]
    else:
        rows += [["best match", "none - nothing cleared the threshold"]]
    rows += [
        ["candidates seen", fmt(search.get("candidates_seen"))],
        ["downloaded", fmt(search.get("candidates_downloaded"))],
        ["with a usable face", fmt(search.get("candidates_with_faces"))],
        ["above threshold", str(len(search.get("matches") or []))],
        ["providers", ", ".join(search.get("providers") or []) or "none responded"],
    ]
    if receipt:
        rows += [
            ["chain backend", fmt(receipt.get("backend"))],
            ["chain id", fmt(receipt.get("chain_id"))],
            ["contract", fmt(receipt.get("contract_address"))],
            ["block", fmt(receipt.get("block_number"))],
            ["tx hash", fmt(receipt.get("tx_hash"))],
            ["gas used", _gas(receipt.get("gas_used")) or "not recorded"],
            ["record id", fmt(receipt.get("record_id"))],
            ["record hash", fmt(receipt.get("record_hash"))],
        ]
    else:
        rows += [["chain", "nothing was anchored for this run"]]
    if run.get("elapsed_seconds") is not None:
        rows += [["total run time", fmt(run.get("elapsed_seconds"), "%.2f s")]]
    return rows


LIMITATIONS = (
    "This is keyword and image search followed by face verification, not true "
    "reverse image search: the providers are asked for pictures by text, and it "
    "is the embedding comparison, not the search engine, that decides identity - "
    "so a post that no query surfaces will never be found, however good the "
    "matcher is. Reddit's unauthenticated JSON API returns 403 to this client, "
    "so a public redlib front-end stands in for it; the permalinks and image URLs "
    "that come back are still genuine Reddit addresses, but the front-end is a "
    "third party in the path. The anchor in this run was written to a local "
    "Hardhat development chain, which is fast and free but does not survive a "
    "node restart - a public testnet or mainnet would be required for a proof "
    "that outlives the machine it was made on. Finally, the 0.363 cosine "
    "threshold is the SFace model's published reference value for same-identity "
    "decisions, chosen for a balance of false accepts against false rejects; it "
    "is a strong indicator and not a forensic guarantee, and no single automated "
    "score should be treated as an identification on its own."
)


# --- PDF machinery -------------------------------------------------------

class _Mark(Flowable):
    """A vector tick or cross - no dingbat font, no glyph coverage surprises."""

    def __init__(self, ok: bool, size: float = 16, color: colors.Color = CYAN):
        Flowable.__init__(self)
        self.ok = ok
        self.size = size
        self.color = color
        self.width = size
        self.height = size

    def draw(self) -> None:
        c = self.canv
        s = self.size
        c.setStrokeColor(self.color)
        c.setLineWidth(max(1.6, s * 0.13))
        c.setLineCap(1)
        c.setLineJoin(1)
        if self.ok:
            p = c.beginPath()
            p.moveTo(s * 0.10, s * 0.52)
            p.lineTo(s * 0.38, s * 0.22)
            p.lineTo(s * 0.92, s * 0.82)
            c.drawPath(p)
        else:
            c.line(s * 0.15, s * 0.15, s * 0.85, s * 0.85)
            c.line(s * 0.15, s * 0.85, s * 0.85, s * 0.15)


class _Doc(BaseDocTemplate):
    """A4 with a fixed header band, footer rule, and 'Page n of m'."""

    def __init__(self, path: str, generated: str, **kw: Any) -> None:
        BaseDocTemplate.__init__(self, path, pagesize=A4,
                                 leftMargin=MARGIN, rightMargin=MARGIN,
                                 topMargin=HEADER_H, bottomMargin=FOOTER_H,
                                 title="FaceChain conclusion report",
                                 author="FaceChain pipeline",
                                 subject="Face identification and blockchain verification",
                                 **kw)
        self.generated = generated
        self._saved: List[Any] = []
        frame = Frame(MARGIN, FOOTER_H, PAGE_W - 2 * MARGIN,
                      PAGE_H - HEADER_H - FOOTER_H, id="body",
                      leftPadding=0, rightPadding=0, topPadding=0, bottomPadding=0)
        self.addPageTemplates([PageTemplate(id="main", frames=[frame],
                                            onPage=self._chrome)])

    def _chrome(self, canv: Any, doc: Any) -> None:
        canv.saveState()
        top = PAGE_H - 14 * mm
        canv.setFillColor(INK)
        canv.setFont("Helvetica-Bold", 17)
        canv.drawString(MARGIN, top, "FACECHAIN")
        wm_w = pdfmetrics.stringWidth("FACECHAIN", "Helvetica-Bold", 17)
        canv.setFillColor(STEEL)
        canv.setFont("Helvetica", 8)
        canv.drawString(MARGIN + wm_w + 8, top + 1.5,
                        "Face Identification and Blockchain Verification")
        canv.setFont("Courier", 7.5)
        canv.drawRightString(PAGE_W - MARGIN, top + 1.5, self.generated)
        canv.setStrokeColor(CYAN)
        canv.setLineWidth(1.1)
        canv.line(MARGIN, top - 6, PAGE_W - MARGIN, top - 6)

        canv.setStrokeColor(HAIRLINE)
        canv.setLineWidth(0.5)
        canv.line(MARGIN, FOOTER_H - 5, PAGE_W - MARGIN, FOOTER_H - 5)
        canv.setFillColor(STEEL)
        canv.setFont("Helvetica", 6.8)
        canv.drawString(MARGIN, FOOTER_H - 13, FOOTER_NOTE)
        canv.setFont("Courier", 7)
        canv.drawRightString(PAGE_W - MARGIN, FOOTER_H - 13,
                             "page %d" % canv.getPageNumber())
        canv.restoreState()


def _styles() -> Dict[str, ParagraphStyle]:
    body = ParagraphStyle("body", fontName="Helvetica", fontSize=9.6, leading=14.2,
                          textColor=INK, alignment=TA_JUSTIFY, spaceAfter=8,
                          splitLongWords=1)
    return {
        "body": body,
        "verdict": ParagraphStyle("verdict", fontName="Helvetica-Bold", fontSize=14.5,
                                  leading=17, textColor=INK, alignment=TA_LEFT),
        "gloss": ParagraphStyle("gloss", fontName="Helvetica", fontSize=9,
                                leading=12.6, textColor=STEEL, alignment=TA_LEFT,
                                spaceBefore=3),
        "h": ParagraphStyle("h", fontName="Helvetica-Bold", fontSize=8,
                            leading=10, textColor=STEEL, spaceAfter=5),
        "key": ParagraphStyle("key", fontName="Helvetica", fontSize=7.8,
                              leading=10, textColor=STEEL),
        "val": ParagraphStyle("val", fontName="Courier", fontSize=7.6,
                              leading=10, textColor=INK, wordWrap="CJK"),
        "cap": ParagraphStyle("cap", fontName="Helvetica", fontSize=7.6,
                              leading=10, textColor=STEEL, alignment=TA_LEFT),
        "capmono": ParagraphStyle("capmono", fontName="Courier", fontSize=7.4,
                                  leading=10, textColor=INK, alignment=TA_LEFT),
        "limits": ParagraphStyle("limits", fontName="Helvetica", fontSize=8,
                                 leading=11.4, textColor=STEEL,
                                 alignment=TA_JUSTIFY, splitLongWords=1),
    }


class _Rule(Flowable):
    def __init__(self, width: float, color: colors.Color = HAIRLINE,
                 thickness: float = 0.6):
        Flowable.__init__(self)
        self.width = width
        self.height = thickness
        self.color = color
        self.thickness = thickness

    def draw(self) -> None:
        self.canv.setStrokeColor(self.color)
        self.canv.setLineWidth(self.thickness)
        self.canv.line(0, 0, self.width, 0)


def _heading(text: str, st: Dict[str, ParagraphStyle], avail: float) -> List[Any]:
    return [Paragraph(text.upper(), st["h"]), _Rule(avail), Spacer(1, 7)]


class _Thumb(Flowable):
    """An ImageReader drawn into a fixed box, with a hairline frame."""

    def __init__(self, reader: ImageReader, width: float, height: float):
        Flowable.__init__(self)
        self.reader = reader
        self.width = width
        self.height = height

    def draw(self) -> None:
        c = self.canv
        try:
            c.drawImage(self.reader, 0, 0, width=self.width, height=self.height,
                        preserveAspectRatio=True, anchor="sw", mask="auto")
        except Exception:  # a file that reads but will not decode
            c.setFillColor(WASH)
            c.rect(0, 0, self.width, self.height, stroke=0, fill=1)
        c.setStrokeColor(HAIRLINE)
        c.setLineWidth(0.6)
        c.rect(0, 0, self.width, self.height, stroke=1, fill=0)


def _thumb(path: Any, box_w: float, box_h: float) -> Optional[Flowable]:
    """Scale an image into a box; return None if it is missing or unreadable."""
    try:
        p = Path(str(path or ""))
        if not path or not p.is_file() or p.stat().st_size == 0:
            return None
        reader = ImageReader(str(p))
        iw, ih = reader.getSize()
        if not iw or not ih:
            return None
        scale = min(box_w / float(iw), box_h / float(ih))
        return _Thumb(reader, iw * scale, ih * scale)
    except Exception:
        return None


def build_conclusion(run: Dict[str, Any], out_path: Path) -> Path:
    """Render the written conclusion for `run` to an A4 PDF at `out_path`."""
    run = run or {}
    out_path = Path(out_path)
    out_path.parent.mkdir(parents=True, exist_ok=True)

    generated = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%SZ")
    st = _styles()
    avail = PAGE_W - 2 * MARGIN
    v = verdict_of(run)
    accent = CYAN if v["passed"] else (STEEL if v.get("neutral") else RED)

    story: List[Any] = []

    # --- Verdict panel ---------------------------------------------------
    mark = _Mark(bool(v["passed"]), 15, accent)
    inner = Table(
        [[mark, Paragraph(_esc(v["headline"]), st["verdict"])],
         ["", Paragraph(_esc(v["gloss"]), st["gloss"])]],
        colWidths=[24, avail - 24 - 26])
    inner.setStyle(TableStyle([
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("TOPPADDING", (0, 0), (-1, -1), 0),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 0),
        ("LEFTPADDING", (0, 0), (-1, -1), 0),
        ("RIGHTPADDING", (0, 0), (-1, -1), 0),
    ]))
    panel = Table([[inner]], colWidths=[avail])
    panel.setStyle(TableStyle([
        ("BOX", (0, 0), (-1, -1), 1.1, accent),
        ("BACKGROUND", (0, 0), (-1, -1), WASH),
        ("LEFTPADDING", (0, 0), (-1, -1), 13),
        ("RIGHTPADDING", (0, 0), (-1, -1), 13),
        ("TOPPADDING", (0, 0), (-1, -1), 12),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 12),
    ]))
    story += [panel, Spacer(1, 16)]

    # --- Prose -----------------------------------------------------------
    story += _heading("Conclusion", st, avail)
    for para in _paragraphs(run, markup=True):
        story.append(Paragraph(para, st["body"]))
    story.append(Spacer(1, 8))

    # --- Evidence table --------------------------------------------------
    rows = [[Paragraph(_esc(k), st["key"]), Paragraph(_esc(val), st["val"])]
            for k, val in evidence_rows(run)]
    table = Table(rows, colWidths=[112, avail - 112], hAlign="LEFT")
    style = [
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("LEFTPADDING", (0, 0), (-1, -1), 6),
        ("RIGHTPADDING", (0, 0), (-1, -1), 6),
        ("TOPPADDING", (0, 0), (-1, -1), 3.5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 3.5),
        ("LINEBELOW", (0, 0), (-1, -2), 0.4, HAIRLINE),
        ("BOX", (0, 0), (-1, -1), 0.6, HAIRLINE),
    ]
    for i in range(0, len(rows), 2):
        style.append(("BACKGROUND", (0, i), (-1, i), WASH))
    table.setStyle(TableStyle(style))
    story += _heading("Evidence", st, avail) + [table, Spacer(1, 14)]

    # --- Thumbnails ------------------------------------------------------
    face = run.get("face") or {}
    best = (run.get("search") or {}).get("best_match") or {}
    cell_w = (avail - 16) / 2.0
    left = _thumb(face.get("thumbnail_path"), cell_w, 150)
    right = _thumb(best.get("local_image_path"), cell_w, 150)
    if left or right:
        sim = best.get("similarity")
        thr = (run.get("search") or {}).get("threshold")
        cap_left = "The submitted face, as cropped and encoded."
        if sim is not None and best:
            cap_right = "The matched image, from %s." % (best.get("platform") or "the post")
        else:
            cap_right = "No matched image for this run."
        cells = [[left or Paragraph("(input crop not available on disk)", st["cap"]),
                  right or Paragraph("(matched image not available on disk)", st["cap"])],
                 [Paragraph(_esc(cap_left), st["cap"]),
                  Paragraph(_esc(cap_right), st["cap"])]]
        thumbs = Table(cells, colWidths=[cell_w, cell_w], hAlign="LEFT")
        thumbs.setStyle(TableStyle([
            ("VALIGN", (0, 0), (-1, 0), "BOTTOM"),
            ("VALIGN", (0, 1), (-1, 1), "TOP"),
            ("ALIGN", (0, 0), (-1, -1), "LEFT"),
            ("LEFTPADDING", (0, 0), (-1, -1), 0),
            ("RIGHTPADDING", (0, 0), (0, -1), 16),
            ("TOPPADDING", (0, 1), (-1, 1), 5),
        ]))
        block: List[Any] = _heading("The two faces compared", st, avail) + [thumbs]
        if isinstance(sim, (int, float)) and isinstance(thr, (int, float)):
            block += [Spacer(1, 4),
                      Paragraph("cosine similarity %.4f  |  identity threshold %.3f"
                                % (sim, thr), st["capmono"])]
        story += [KeepTogether(block), Spacer(1, 14)]

    # --- Limitations -----------------------------------------------------
    story += _heading("Limitations", st, avail)
    story.append(Paragraph(LIMITATIONS, st["limits"]))

    doc = _Doc(str(out_path), generated)
    doc.build(story)
    return out_path


def build_conclusion_from_file(run_json: Path, out_path: Path) -> Path:
    """Convenience: render straight from a saved out/run-*.json."""
    import json
    data = json.loads(Path(run_json).read_text(encoding="utf-8"))
    return build_conclusion(data, Path(out_path))
